### ISSUE TITLE
Bun install results in charts not being shown

### ISSUE THREAD

**Issue by philtsip** [RhysSullivan/hogchat#1]
PNPM install works great.

But bun install results in charts not being shown (screenshot).

Perhaps one of the dependencies is not included in package.json?

![CleanShot 2024-03-02 at 13 30 14@2x](https://github.com/RhysSullivan/hogchat/assets/375058/c94cfa8f-463b-490b-ac76-b6d07da13f49)

**Comment by RhysSullivan** [comment]
This might not be a bun issue, it might be the key to use for the date column not being set correctly

@philtsip for debugging it further I'd recommend adding some logging statements around this section of query-chart.tsx to see what the values of formatted and timeField are 

![image](https://github.com/RhysSullivan/hogchat/assets/39114868/1850e3df-9d1d-43ba-bf02-a6291fff058c)

It's got to convert it from a random SQL query to the right format for the charts so I could see that causing a problem

**Comment by RhysSullivan** [comment]
@philtsip pushed a commit that I think should fix that query & chart not showing - give it a pull and see if that fixes it

**Comment by philtsip** [comment]
Yup. Works perfectly now. Thank you! :)
